/**
 * Category mapping for all tests
 * Maps test IDs to their categories
 */

export const TEST_CATEGORIES = {
  // Love & Relationships (연애 & 관계)
  '1': 'love',
  '24': 'love',
  '31': 'love',
  '32': 'love',
  '33': 'love',
  '37': 'love',
  '38': 'love',
  '100': 'love',
  '101': 'love',
  '102': 'love',
  '103': 'love',
  '104': 'love',
  '105': 'love',
  '106': 'love',
  '107': 'love',
  '108': 'love',
  '109': 'love',
  '110': 'love',
  '111': 'love',
  '112': 'love',
  '113': 'love',
  '114': 'love',
  '115': 'love',
  '116': 'love',
  '117': 'love',
  '118': 'love',
  '119': 'love',
  '120': 'love',
  '121': 'love',
  '122': 'love',

  // Personality & Psychology (성격 & 심리)
  '6': 'personality',
  '22': 'personality',
  '34': 'personality',
  '35': 'personality',
  '36': 'personality',
  '60': 'personality',
  '84': 'personality',
  '85': 'personality',
  '86': 'personality',
  '87': 'personality',
  '88': 'personality',
  '89': 'personality',
  '90': 'personality',
  '91': 'personality',
  '92': 'personality',
  '93': 'personality',
  '94': 'personality',
  '95': 'personality',
  '96': 'personality',
  '97': 'personality',
  '98': 'personality',
  '99': 'personality',
  '123': 'personality',
  '124': 'personality',
  '125': 'personality',
  '126': 'personality',

  // Learning & Education (학습 & 교육)
  '23': 'learning',
  '25': 'learning',
  '26': 'learning',
  '27': 'learning',
  '28': 'learning',
  '29': 'learning',
  '30': 'learning',
  '61': 'learning',
  '62': 'learning',
  '63': 'learning',
  '64': 'learning',
  '65': 'learning',
  '66': 'learning',
  '67': 'learning',
  '68': 'learning',
  '69': 'learning',
  '70': 'learning',
  '71': 'learning',
  '72': 'learning',
  '73': 'learning',
  '74': 'learning',
  '75': 'learning',
  '76': 'learning',
  '77': 'learning',
  '78': 'learning',
  '79': 'learning',
  '80': 'learning',
  '81': 'learning',
  '82': 'learning',
  '83': 'learning',

  // Lifestyle (라이프스타일)
  '2': 'lifestyle',
  '3': 'lifestyle',
  '4': 'lifestyle',
  '8': 'lifestyle',
  '9': 'lifestyle',
  '10': 'lifestyle',
  '11': 'lifestyle',
  '12': 'lifestyle',
  '13': 'lifestyle',
  '14': 'lifestyle',
  '15': 'lifestyle',
  '16': 'lifestyle',
  '17': 'lifestyle',
  '18': 'lifestyle',
  '19': 'lifestyle',
  '20': 'lifestyle',
  '21': 'lifestyle',

  // Trends & Memes (트렌드 & 밈)
  '5': 'meme-trend',
  '7': 'meme-trend',
  '39': 'meme-trend',
  '40': 'meme-trend',
  '41': 'meme-trend',
  '42': 'meme-trend',
  '43': 'meme-trend',
  '44': 'meme-trend',
  '45': 'meme-trend',
  '46': 'meme-trend',
  '47': 'meme-trend',
  '48': 'meme-trend',
  '49': 'meme-trend',

  // Hobbies & Entertainment (취미 & 엔터)
  '50': 'hobby-entertainment',
  '51': 'hobby-entertainment',
  '52': 'hobby-entertainment',
  '53': 'hobby-entertainment',
  '54': 'hobby-entertainment',
  '55': 'hobby-entertainment',
  '56': 'hobby-entertainment',
  '57': 'hobby-entertainment',
  '58': 'hobby-entertainment',
  '59': 'hobby-entertainment',
};

/**
 * Get category for a test ID
 * @param {string} testId - Test ID
 * @returns {string} Category ID
 */
export function getCategoryForTest(testId) {
  return TEST_CATEGORIES[testId] || 'other';
}
